`define EXCEPTION_NOP               5'd0
`define EXCEPTION_ERET              5'd1
`define EXCEPTION_SYSCALL           5'd2
`define EXCEPTION_BREAK             5'd3
`define EXCEPTION_INST_ADEL         5'd4
`define EXCEPTION_INTERRUPT         5'd27
`define EXCEPTION_DATA_ADEL         5'd28
`define EXCEPTION_DATA_ADES         5'd29
`define EXCEPTION_OVERFLOW          5'd30
`define EXCEPTION_RESERVED_INST     5'd31